# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en
de:
  languageCode: de-de
  contentDir: content/de
  menu:
    main:
      - name: Tour
        url: tour
        weight: 10
      - name: Blog
        url: post
        weight: 20
      - name: Abschlüssarbeiten
        url: theses
        weight: 30
      - name: Lehre
        url: lehre
        weight: 40
      - name: Kontakt
        url: contact
        weight: 60

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
