# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en
  contentDir: content/en
de:
  languageCode: de
  contentDir: content/de
  menu:
    main:
      - name: Home
        url: /
        weight: 10
      - name: Blog
        url: post
        weight: 20
      - name: Personen
        url: people
        weight: 30
      - name: Lehre
        url: lehre
        weight: 40
      - name: Abschlüssarbeiten
        url: theses
        weight: 50
      - name: Projekte&nbsp;/&nbsp;Forschungsthemen
        url: projects
        weight: 60
      - name: Publications
        url: publication
        weight: 50
      - name: Awards
        url: awards
        weight: 60
      - name: Kontakt
        url: contact
        weight: 70
uk:
  languageCode: uk
  contentDir: content/uk
  menu:
    main:
      - name: Home
        url: /
        weight: 10
      - name: Блог
        url: post
        weight: 20
      - name: Люди
        url: people
        weight: 30
      - name: Навчання
        url: lehre
        weight: 40
      - name: Дипломні&nbsp;роботи
        url: theses
        weight: 50
      - name: Проєкти&nbsp;та&nbsp;теми&nbsp;досліджень  # теми наукової роботи? 
        url: projects
        weight: 60
      - name: Публікації
        url: publication
        weight: 50
      - name: Нагороди
        url: awards
        weight: 60
      - name: Контакти
        url: contact
        weight: 70


# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
