# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# Non-English menus in languages.yaml - SH

main:
    #  - name: Tour
    #url: tour
    #weight: 10
  - name: Home
    url: /
    weight: 10
  - name: Blog
    url: post
    weight: 20
  - name: People
    url: people
    weight: 30
  - name: Courses
    url: lehre
    weight: 40
  - name: Theses
    url: theses
    weight: 50
  - name: Projects
    url: projects
    weight: 60
  - name: Publications
    url: publication
    weight: 50
    identifier: pub
  - name: Publications
    url: publication
    weight: 1
    parent: pub
  - name: Awards
    url: awards
    weight: 2
    parent: pub
    #- name: Awards
    #url: awards
    #weight: 60
  - name: Contact
    url: contact
    weight: 70
