project:
  type: website
  preview:
    port: 9090
    browser: false
  post-render: _extensions/redirect_root_to_de.py

profile:
  default: de
  group:
    - [de, en, ua]

website:
  title: "AnhaltAI"
  favicon: "logos/anhaltai-icon-red_blue-transparent.png"
  navbar:
    background: light
    left:
      - text: Home
        href: index.qmd
  page-footer:
    background: light
    center:
      - text: "{{< iconify mdi:github >}} anhaltai"
        href: https://github.com/anhaltai
      - text: "{{< iconify noto-v1:hugging-face >}} anhaltai"
        href: https://huggingface.co/anhaltai
      - text: "Impressum"
        href: impressum.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false
