project:
  type: website

website:
  title: "AnhaltAI"
  favicon: "logos/anhaltai-icon-red_blue-transparent.png"
  navbar:
    background: light
    left:
      - text: Home
        href: index.qmd
  page-footer:
    background: light
    center:
      - text: "Impressum"
        href: impressum.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
