---
title: "Impressum"
---

## Herausgeber
Die Hochschule Anhalt ist eine Körperschaft des Öffentlichen Rechts. Sie wird durch den Präsidenten Prof. Dr. Jörg Bagdahn gesetzlich vertreten.

Inhaltlich Verantwortlicher für den Internetauftritt [http://anhalt.ai/](http://anhalt.ai/) gemäß § 55 Abs. 2 RStV:
Prof. Dr. Christian Hänig

Hochschule Anhalt<br/>
University of Applied Sciences<br/>
Bernburger Straße 55<br/>
06366 Köthen

E-Mail: [info@hs-anhalt.de](mailto:info@hs-anhalt.de)<br/>
Web: [https://www.hs-anhalt.de/](https://www.hs-anhalt.de/)

Die zuständige Aufsichtsbehörde:

Ministerium für Wissenschaft, Energie, Klimaschutz und Umwelt des Landes Sachsen-Anhalt<br/>
Leipziger Straße 58<br/>
39112 Magdeburg

E-Mail: [poststelle@mwu.sachsen-anhalt.de](mailto:poststelle@mwu.sachsen-anhalt.de)<br/>
Web: [https://mwu.sachsen-anhalt.de/](https://mwu.sachsen-anhalt.de/)

Umsatzsteuer-Ident-Nummer: DE814092585

## Haftungsausschluss
Die inhaltliche Verantwortung der einzelnen WWW-Seiten liegt bei den jeweiligen informationseinstellenden Einrichtungen oder Personen. Eine Haftung für die Aktualität, Korrektheit, Vollständigkeit und Qualität dieser Webseiten kann trotz sorgfältiger Prüfung nicht übernommen werden. Die Hochschule Anhalt übernimmt insbesondere keinerlei Haftung für eventuelle Schäden oder Konsequenzen, die durch die direkte oder indirekte Nutzung der angebotenen Inhalte entstehen.

## Rechtswirksamkeit des Haftungsausschlusses
Dieser Haftungsausschluss ist als Teil des Internetangebotes zu betrachten, von dem aus auf diesen Text verwiesen wurde. Sollten Teile oder einzelne Formulierungen des Textes der geltenden Rechtslage nicht, nicht mehr oder nicht vollständig entsprechen, gilt das rechtlich Gewollte und bleiben die übrigen Teile des Dokuments in ihrem Inhalt und ihrer Gültigkeit davon unberührt.

## Urheberrecht
Alle im Internetangebot der Hochschule Anhalt veröffentlichten Inhalte (Layout, Texte, Bilder, Grafiken, Tondokumente, Videosequenzen usw.) unterliegen dem Urheberrecht. Jede vom Urheberrechtsgesetz nicht zugelassene Verwertung bedarf vorheriger ausdrücklicher Zustimmung. Dies gilt insbesondere für Vervielfältigung, Bearbeitung, Übersetzung, Einspeicherung, Verarbeitung bzw. (öffentliche) Wiedergabe von Inhalten in Datenbanken oder anderen elektronischen Medien und Systemen. Fotokopien und Downloads von Web-Seiten für den privaten, wissenschaftlichen und nicht kommerziellen Gebrauch dürfen hergestellt werden. Alle innerhalb des Internetangebotes genannten und ggf. durch Dritte geschützten Marken und Warenzeichen unterliegen uneingeschränkt den Bestimmungen des jeweils gültigen Kennzeichenrechts und den Besitzrechten der jeweiligen eingetragenen Eigentümer. Allein aufgrund der bloßen Nennung ist nicht der Schluss zu ziehen, dass Markenzeichen nicht durch Rechte Dritter geschützt sind.

## Datenschutz
[zum Datenschutz](https://www.hs-anhalt.de/datenschutz.html)
